language: python
python: 3.6
git:
  depth: false
cache: 
  directories:
    - $HOME/.cache/pip
    - /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages
    - /home/travis/virtualenv/python3.6.3/bin
    - /home/travis/data
install:
  - pip install mkdocs mkdocs-material
  - echo -e "machine github.com\n  login ${github_token}" > ~/.netrc
  - cd /home/travis/data && rm -rf dl-engineer-guidebook
  - git clone https://github.com/ypwhs/dl-engineer-guidebook
script:
  - cd /home/travis/data/dl-engineer-guidebook
  - mkdocs gh-deploy --clean
