language: python
python: 3.6
git:
  depth: false
cache: 
  directories:
    - $HOME/.cache/pip
install:
  - pip install mkdocs mkdocs-material
  - echo -e "machine github.com\n  login ${github_token}" > ~/.netrc
  - git fetch origin site
script:
  - mkdocs gh-deploy --clean
